### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by lukas-gitl** [AdrianSchneider/Qissues-Interactive#2]
![issue](https://cloud.githubusercontent.com/assets/7819023/25103032/c22e6d1c-236f-11e7-9592-e49cc844d021.png)

**Comment by lukas-gitl** [comment]
Not sure what I'm doing wrong here...?

**Comment by lukas-gitl** [comment]
22 silly fetchPackageMetaData Error: Registry returned 404 for GET on https://registry.npmjs.org/quissues
22 silly fetchPackageMetaData     at makeError (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:302:12)

**Comment by AdrianSchneider** [comment]
`qissues` without the `u`

**Comment by lukas-gitl** [comment]
Gawd I feel stupid now ;)

And I totally didn't remember that I had to install as sudo... anyways, time to experiement!
